--
-- PostgreSQL database dump
--

\restrict BVIDiuOOoJmcpWybptcyLrcDNGoTb7Tg5I5XSfY64tmmcNYKerQswyCyccmMcwt

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts_interests; Type: TABLE; Schema: public; Owner: ecolodge_user
--

CREATE TABLE public.accounts_interests (
    id bigint CONSTRAINT accounts_interest_id_not_null NOT NULL,
    name character varying CONSTRAINT accounts_interest_name_not_null NOT NULL
);


ALTER TABLE public.accounts_interests OWNER TO ecolodge_user;

--
-- Name: accounts_interest_id_seq; Type: SEQUENCE; Schema: public; Owner: ecolodge_user
--

ALTER TABLE public.accounts_interests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_interest_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_profile; Type: TABLE; Schema: public; Owner: ecolodge_user
--

CREATE TABLE public.accounts_profile (
    id bigint NOT NULL,
    first_name character varying NOT NULL,
    last_name character varying NOT NULL,
    phone_number character varying(11) NOT NULL,
    owner boolean NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.accounts_profile OWNER TO ecolodge_user;

--
-- Name: accounts_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: ecolodge_user
--

ALTER TABLE public.accounts_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_profile_interests; Type: TABLE; Schema: public; Owner: ecolodge_user
--

CREATE TABLE public.accounts_profile_interests (
    id bigint NOT NULL,
    profile_id bigint NOT NULL,
    interests_id bigint CONSTRAINT accounts_profile_interests_interest_id_not_null NOT NULL
);


ALTER TABLE public.accounts_profile_interests OWNER TO ecolodge_user;

--
-- Name: accounts_profile_interests_id_seq; Type: SEQUENCE; Schema: public; Owner: ecolodge_user
--

ALTER TABLE public.accounts_profile_interests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_profile_interests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user; Type: TABLE; Schema: public; Owner: ecolodge_user
--

CREATE TABLE public.accounts_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.accounts_user OWNER TO ecolodge_user;

--
-- Name: accounts_user_groups; Type: TABLE; Schema: public; Owner: ecolodge_user
--

CREATE TABLE public.accounts_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.accounts_user_groups OWNER TO ecolodge_user;

--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: ecolodge_user
--

ALTER TABLE public.accounts_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE; Schema: public; Owner: ecolodge_user
--

ALTER TABLE public.accounts_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_user_permissions; Type: TABLE; Schema: public; Owner: ecolodge_user
--

CREATE TABLE public.accounts_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.accounts_user_user_permissions OWNER TO ecolodge_user;

--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: ecolodge_user
--

ALTER TABLE public.accounts_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: ecolodge_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO ecolodge_user;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: ecolodge_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: ecolodge_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO ecolodge_user;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: ecolodge_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: ecolodge_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO ecolodge_user;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: ecolodge_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: ecolodge_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO ecolodge_user;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: ecolodge_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: ecolodge_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO ecolodge_user;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: ecolodge_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: ecolodge_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO ecolodge_user;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: ecolodge_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: ecolodge_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO ecolodge_user;

--
-- Name: lodges_lodge; Type: TABLE; Schema: public; Owner: ecolodge_user
--

CREATE TABLE public.lodges_lodge (
    id bigint NOT NULL,
    title character varying NOT NULL,
    slug character varying(50) NOT NULL,
    description text NOT NULL,
    province character varying NOT NULL,
    city character varying NOT NULL,
    address text NOT NULL,
    capacity integer NOT NULL,
    price integer NOT NULL,
    active boolean NOT NULL,
    status character varying NOT NULL,
    owner_id bigint NOT NULL,
    CONSTRAINT lodges_lodge_capacity_e06950bf_check CHECK ((capacity >= 0)),
    CONSTRAINT lodges_lodge_price_071e04d1_check CHECK ((price >= 0))
);


ALTER TABLE public.lodges_lodge OWNER TO ecolodge_user;

--
-- Name: lodges_lodge_id_seq; Type: SEQUENCE; Schema: public; Owner: ecolodge_user
--

ALTER TABLE public.lodges_lodge ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lodges_lodge_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lodges_lodge_interests; Type: TABLE; Schema: public; Owner: ecolodge_user
--

CREATE TABLE public.lodges_lodge_interests (
    id bigint NOT NULL,
    lodge_id bigint NOT NULL,
    interests_id bigint CONSTRAINT lodges_lodge_interests_interest_id_not_null NOT NULL
);


ALTER TABLE public.lodges_lodge_interests OWNER TO ecolodge_user;

--
-- Name: lodges_lodge_interests_id_seq; Type: SEQUENCE; Schema: public; Owner: ecolodge_user
--

ALTER TABLE public.lodges_lodge_interests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lodges_lodge_interests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lodges_lodgeimage; Type: TABLE; Schema: public; Owner: ecolodge_user
--

CREATE TABLE public.lodges_lodgeimage (
    id bigint NOT NULL,
    image character varying(100),
    lodge_id bigint NOT NULL
);


ALTER TABLE public.lodges_lodgeimage OWNER TO ecolodge_user;

--
-- Name: lodges_lodgeimage_id_seq; Type: SEQUENCE; Schema: public; Owner: ecolodge_user
--

ALTER TABLE public.lodges_lodgeimage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lodges_lodgeimage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservations_reservation; Type: TABLE; Schema: public; Owner: ecolodge_user
--

CREATE TABLE public.reservations_reservation (
    id bigint NOT NULL,
    guest_count integer NOT NULL,
    check_in date NOT NULL,
    check_out date NOT NULL,
    total_price integer NOT NULL,
    status boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    lodge_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT reservations_reservation_guest_count_check CHECK ((guest_count >= 0)),
    CONSTRAINT reservations_reservation_total_price_check CHECK ((total_price >= 0))
);


ALTER TABLE public.reservations_reservation OWNER TO ecolodge_user;

--
-- Name: reservations_reservation_id_seq; Type: SEQUENCE; Schema: public; Owner: ecolodge_user
--

ALTER TABLE public.reservations_reservation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservations_reservation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: accounts_interests; Type: TABLE DATA; Schema: public; Owner: ecolodge_user
--

COPY public.accounts_interests (id, name) FROM stdin;
1	جنگل
2	کوهستان
3	دریا
4	کویر
5	رودخانه
6	آبشار
7	حیات وحش
8	کمپینگ
9	عکاسی
10	آرامش
11	غذای محلی
\.


--
-- Data for Name: accounts_profile; Type: TABLE DATA; Schema: public; Owner: ecolodge_user
--

COPY public.accounts_profile (id, first_name, last_name, phone_number, owner, user_id) FROM stdin;
3				t	4
7				f	8
8				f	9
9				f	10
1	hasan			t	3
2	admin	kh	09335067699	t	1
4	s.liloo	gh	123456	t	5
5	SK	G	0912000000	t	6
6				f	7
\.


--
-- Data for Name: accounts_profile_interests; Type: TABLE DATA; Schema: public; Owner: ecolodge_user
--

COPY public.accounts_profile_interests (id, profile_id, interests_id) FROM stdin;
2	1	2
3	1	6
4	3	11
5	3	3
6	3	7
18	4	4
19	5	11
20	5	4
21	5	6
22	6	1
23	6	5
24	6	6
25	6	10
26	6	11
27	1	5
35	2	9
36	2	3
\.


--
-- Data for Name: accounts_user; Type: TABLE DATA; Schema: public; Owner: ecolodge_user
--

COPY public.accounts_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
5	pbkdf2_sha256$1200000$nGbFeeZhzbxyfU43AA4S2h$BTb4B0SisYk46iahVVtwe0j3Ld0BcRL9QgSxI3jJ9EI=	2026-08-14 00:12:14.062175+03:30	f	s.liloo			leayleh@gmail.com	f	t	2026-08-13 23:50:14.465771+03:30
6	pbkdf2_sha256$1200000$wrJFSkZ6QdD2EW4IwiFf2n$wE5cyfjjfrMmg9H3ZXq6mctdfHGUNQFWjvy5B80+iks=	2026-08-14 00:48:28.71104+03:30	f	kiku			kawthar.toto@gmail.com	t	t	2026-08-14 00:26:00+03:30
7	pbkdf2_sha256$1200000$xMPMaVEqvce71Ha0q2DEgx$ji3HfMpEspTWeBI98yLKVucyfeU9HPGSDRp4qt20oWI=	2026-08-23 20:27:51.592601+03:30	f	shg			hamideh.ghayeni@gmail.com	f	t	2026-08-23 20:25:53.610178+03:30
2	pbkdf2_sha256$1200000$Fwb1L8gyARFlpR2RraTrrH$iu5EN7xdI97NFWivJF8bTf/e9pBnXU5Ddj14ukrB87A=	2026-08-01 16:44:05.052663+03:30	f	aa			aa@email.com	f	t	2026-08-01 16:43:49.884012+03:30
10	pbkdf2_sha256$1200000$Tou2UJKIj5M9TCEVXC6Xce$Vzq/2sg4KdDTCIBjBDHNfuvS4FzllH7dkh6ssW6iFGU=	2026-09-05 21:45:55.483395+03:30	f	ali			ali@gmail.com	f	t	2026-09-05 21:02:32.236892+03:30
1	pbkdf2_sha256$1200000$KcqFd7LMyymrLROJBLZTNu$tWm494yRxSkx9rgBmfnNRCWDBVppc1Q91Xl2pPTCeDI=	2026-09-07 18:52:18.190964+03:30	t	admin			admin@site.com	t	t	2026-07-25 21:49:18.93178+03:30
3	pbkdf2_sha256$1200000$lDJJKg8fg1TnvNCijOrASx$Dg2ezzn2j4mvqe5kyt/6WiJWsjmfJdB1A5+3+l7oRL8=	2026-09-07 18:53:12.145888+03:30	f	hasan			hasan@gmail.com	f	t	2026-08-01 17:02:11.089024+03:30
8	pbkdf2_sha256$1200000$bU4WWryLBZNzSi6dlI8JlT$38+aB/nOWB97KjseoI5UgFwu2H9rIhZ6an2sk1+cjpw=	\N	f	elahe			elahe@email.com	f	t	2026-08-27 23:53:22.217476+03:30
4	pbkdf2_sha256$1200000$9mxYc8t4VTOWE4cUxcaI9n$4bg47CTJZ1icyY/Gow/ZgQE+IJZIWKMNsI+4wsfq2cg=	2026-08-14 00:10:53.38628+03:30	f	adminn			zeinobeh@gmail.com	f	t	2026-08-03 23:33:31.614155+03:30
9	pbkdf2_sha256$1200000$L3VNLJ7edZvQNo18NYTZup$aaudIRqqVc1U6QpEwV7ROnOzekW5tryehGQIcSgwFkQ=	2026-08-27 23:58:04.299562+03:30	f	ehsan			ehsan@gmail.com	f	t	2026-08-27 23:57:41.70698+03:30
\.


--
-- Data for Name: accounts_user_groups; Type: TABLE DATA; Schema: public; Owner: ecolodge_user
--

COPY public.accounts_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: accounts_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: ecolodge_user
--

COPY public.accounts_user_user_permissions (id, user_id, permission_id) FROM stdin;
1	6	1
2	6	2
3	6	3
4	6	4
5	6	5
6	6	6
7	6	7
8	6	8
9	6	9
10	6	10
11	6	11
12	6	12
13	6	13
14	6	14
15	6	15
16	6	16
17	6	17
18	6	18
19	6	19
20	6	20
21	6	21
22	6	22
23	6	23
24	6	24
25	6	25
26	6	26
27	6	27
28	6	28
29	6	29
30	6	30
31	6	31
32	6	32
33	6	33
34	6	34
35	6	35
36	6	36
37	6	37
38	6	38
39	6	39
40	6	40
41	6	41
42	6	42
43	6	43
44	6	44
45	6	45
46	6	46
47	6	47
48	6	48
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: ecolodge_user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: ecolodge_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: ecolodge_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add interest	6	add_interest
22	Can change interest	6	change_interest
23	Can delete interest	6	delete_interest
24	Can view interest	6	view_interest
25	Can add user	8	add_user
26	Can change user	8	change_user
27	Can delete user	8	delete_user
28	Can view user	8	view_user
29	Can add profile	7	add_profile
30	Can change profile	7	change_profile
31	Can delete profile	7	delete_profile
32	Can view profile	7	view_profile
33	Can add اقامتگاه	9	add_lodge
34	Can change اقامتگاه	9	change_lodge
35	Can delete اقامتگاه	9	delete_lodge
36	Can view اقامتگاه	9	view_lodge
37	Can add lodge image	10	add_lodgeimage
38	Can change lodge image	10	change_lodgeimage
39	Can delete lodge image	10	delete_lodgeimage
40	Can view lodge image	10	view_lodgeimage
41	Can add interests	6	add_interests
42	Can change interests	6	change_interests
43	Can delete interests	6	delete_interests
44	Can view interests	6	view_interests
45	Can add reservation	11	add_reservation
46	Can change reservation	11	change_reservation
47	Can delete reservation	11	delete_reservation
48	Can view reservation	11	view_reservation
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: ecolodge_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-07-29 23:32:12.881678+03:30	1	اقامتگاه 1	1	[{"added": {}}, {"added": {"name": "lodge image", "object": "LodgeImage object (1)"}}, {"added": {"name": "lodge image", "object": "LodgeImage object (2)"}}]	9	1
2	2026-07-29 23:40:25.104686+03:30	2	اقامتگاه چند طبقه	1	[{"added": {}}, {"added": {"name": "lodge image", "object": "LodgeImage object (3)"}}]	9	1
3	2026-07-29 23:53:35.787569+03:30	3	اقامتگاه 3	1	[{"added": {}}, {"added": {"name": "lodge image", "object": "LodgeImage object (4)"}}, {"added": {"name": "lodge image", "object": "LodgeImage object (5)"}}]	9	1
4	2026-07-30 09:55:49.59466+03:30	4	اقامتگاه 4	1	[{"added": {}}, {"added": {"name": "lodge image", "object": "LodgeImage object (6)"}}]	9	1
5	2026-07-30 09:55:57.012847+03:30	3	اقامتگاه 3	2	[{"changed": {"fields": ["Status"]}}]	9	1
6	2026-07-30 13:16:54.053009+03:30	5	hrhlj'hi 5	1	[{"added": {}}, {"added": {"name": "lodge image", "object": "LodgeImage object (7)"}}]	9	1
7	2026-07-30 13:40:25.59938+03:30	6	اقامتگاه 6 لورم ایپسوم متن ساختگی با تولید سادگی	1	[{"added": {}}, {"added": {"name": "lodge image", "object": "LodgeImage object (8)"}}]	9	1
8	2026-07-30 21:31:13.293272+03:30	6	اقامتگاه 6 لورم ایپسوم متن ساختگی با تولید سادگی	2	[{"changed": {"fields": ["Active"]}}]	9	1
9	2026-07-30 21:32:23.867335+03:30	6	اقامتگاه 6 لورم ایپسوم متن ساختگی با تولید سادگی	2	[{"changed": {"fields": ["Active"]}}]	9	1
10	2026-08-01 15:33:13.332772+03:30	1	جنگل	1	[{"added": {}}]	6	1
11	2026-08-01 15:33:14.958029+03:30	1	جنگل	2	[]	6	1
12	2026-08-01 15:33:21.126609+03:30	2	کوهستان	1	[{"added": {}}]	6	1
13	2026-08-01 15:33:27.386656+03:30	3	دریا	1	[{"added": {}}]	6	1
14	2026-08-01 15:33:33.571783+03:30	4	کویر	1	[{"added": {}}]	6	1
15	2026-08-01 15:33:50.955241+03:30	5	رودخانه	1	[{"added": {}}]	6	1
16	2026-08-01 15:33:56.001103+03:30	6	آبشار	1	[{"added": {}}]	6	1
17	2026-08-01 15:34:13.846449+03:30	7	حیات وحش	1	[{"added": {}}]	6	1
18	2026-08-01 15:34:20.720548+03:30	8	کمپینگ	1	[{"added": {}}]	6	1
19	2026-08-01 15:34:34.726111+03:30	9	عکاسی	1	[{"added": {}}]	6	1
20	2026-08-01 15:34:40.222434+03:30	10	آرامش	1	[{"added": {}}]	6	1
21	2026-08-01 15:34:53.764667+03:30	11	غذای محلی	1	[{"added": {}}]	6	1
22	2026-08-03 00:12:29.390806+03:30	14	اقامتگاه حسن 5	2	[{"changed": {"fields": ["Status"]}}]	9	1
23	2026-08-03 00:22:01.989923+03:30	2	Profile object (2)	1	[{"added": {}}]	7	1
24	2026-08-03 16:45:27.984993+03:30	14	اقامتگاه حسن 5	2	[{"changed": {"fields": ["Status"]}}]	9	1
25	2026-08-03 16:46:05.210108+03:30	14	اقامتگاه حسن 5	2	[{"added": {"name": "lodge image", "object": "LodgeImage object (9)"}}, {"added": {"name": "lodge image", "object": "LodgeImage object (10)"}}, {"added": {"name": "lodge image", "object": "LodgeImage object (11)"}}]	9	1
26	2026-08-03 17:59:20.522572+03:30	14	اقامتگاه حسن 5	2	[{"changed": {"fields": ["Status"]}}]	9	1
27	2026-08-03 17:59:27.298646+03:30	13	اقامتگاه حسن 4	2	[{"changed": {"fields": ["Status"]}}]	9	1
28	2026-08-03 17:59:34.239286+03:30	12	اقامتگاه حسن 3	2	[{"changed": {"fields": ["Status"]}}]	9	1
29	2026-08-03 17:59:44.301972+03:30	7	ytr	2	[{"changed": {"fields": ["Status"]}}]	9	1
30	2026-08-03 18:01:32.916826+03:30	13	اقامتگاه حسن 4	2	[{"changed": {"fields": ["Status"]}}]	9	1
31	2026-08-03 18:01:41.741358+03:30	10	اقامتگاه حسن 2	2	[{"changed": {"fields": ["Status"]}}]	9	1
32	2026-08-03 18:01:49.010853+03:30	8	اقامتگاه حسن 1	2	[{"changed": {"fields": ["Status"]}}]	9	1
33	2026-08-03 23:01:26.182371+03:30	15	اقامتگاه رامسر حسن	2	[{"changed": {"fields": ["Status"]}}]	9	1
34	2026-08-03 23:30:02.618847+03:30	15	اقامتگاه رامسر حسن	2	[{"changed": {"fields": ["Status"]}}]	9	1
35	2026-08-03 23:30:08.045366+03:30	6	اقامتگاه 6 لورم ایپسوم متن ساختگی با تولید سادگی	2	[{"changed": {"fields": ["Status"]}}]	9	1
36	2026-08-03 23:30:17.071665+03:30	7	ytr	2	[{"changed": {"fields": ["Status"]}}]	9	1
37	2026-08-03 23:30:23.342113+03:30	5	hrhlj'hi 5	2	[{"changed": {"fields": ["Status"]}}]	9	1
38	2026-08-03 23:30:29.791603+03:30	4	اقامتگاه 4	2	[{"changed": {"fields": ["Status"]}}]	9	1
39	2026-08-03 23:30:35.162211+03:30	3	اقامتگاه 3	2	[{"changed": {"fields": ["Status"]}}]	9	1
40	2026-08-03 23:30:41.17152+03:30	2	اقامتگاه چند طبقه	2	[{"changed": {"fields": ["Status"]}}]	9	1
41	2026-08-03 23:30:46.369861+03:30	1	اقامتگاه 1	2	[{"changed": {"fields": ["Status"]}}]	9	1
42	2026-08-11 18:20:46.057223+03:30	9	Reservation object (9)	3		11	1
43	2026-08-14 00:34:22.183707+03:30	10	Reservation object (10)	1	[{"added": {}}]	11	1
44	2026-08-14 00:40:41.483849+03:30	17	بهشت دنیوی	2	[{"changed": {"fields": ["Status"]}}]	9	1
45	2026-08-14 00:42:39.081574+03:30	12	اقامتگاه حسن 3	2	[{"changed": {"fields": ["Province"]}}, {"added": {"name": "lodge image", "object": "LodgeImage object (19)"}}]	9	1
46	2026-08-14 00:48:07.362004+03:30	6	kiku	2	[{"changed": {"fields": ["Staff status", "User permissions"]}}]	8	1
47	2026-08-14 00:53:44.021893+03:30	14	اقامتگاه حسن 5	2	[{"changed": {"fields": ["Province"]}}, {"changed": {"name": "lodge image", "object": "LodgeImage object (11)", "fields": ["Image"]}}]	9	6
48	2026-08-14 00:54:11.357567+03:30	14	اقامتگاه حسن 5	2	[{"deleted": {"name": "lodge image", "object": "LodgeImage object (None)"}}]	9	6
49	2026-08-14 01:17:26.623926+03:30	18	خانه آبی	2	[{"changed": {"fields": ["Status"]}}]	9	6
50	2026-08-14 01:17:55.78919+03:30	18	خانه آبی	2	[{"changed": {"fields": ["Status"]}}]	9	6
51	2026-09-02 21:06:17.827444+03:30	19	لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم	2	[{"changed": {"fields": ["\\u0648\\u0636\\u0639\\u06cc\\u062a"]}}]	9	1
52	2026-09-06 18:46:07.827747+03:30	12	جنگل	1	[{"added": {}}]	6	1
53	2026-09-06 19:22:12.86569+03:30	12	جنگل	3		6	1
54	2026-09-07 18:34:45.845694+03:30	20	اقامتگاه هفتادم	2	[{"changed": {"fields": ["\\u0648\\u0636\\u0639\\u06cc\\u062a"]}}]	9	1
55	2026-09-07 18:34:55.109668+03:30	19	لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم	2	[{"changed": {"fields": ["\\u0648\\u0636\\u0639\\u06cc\\u062a"]}}]	9	1
56	2026-09-07 18:35:20.20048+03:30	16	our home	2	[{"changed": {"fields": ["\\u0627\\u0633\\u062a\\u0627\\u0646", "\\u0648\\u0636\\u0639\\u06cc\\u062a"]}}]	9	1
57	2026-09-07 18:35:31.455577+03:30	4	اقامتگاه 4	2	[{"changed": {"fields": ["\\u0641\\u0639\\u0627\\u0644 \\u0628\\u0648\\u062f\\u0646", "\\u0648\\u0636\\u0639\\u06cc\\u062a"]}}]	9	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: ecolodge_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	contenttypes	contenttype
5	sessions	session
7	accounts	profile
8	accounts	user
9	lodges	lodge
10	lodges	lodgeimage
6	accounts	interests
11	reservations	reservation
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: ecolodge_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-07-25 21:47:44.389986+03:30
2	contenttypes	0002_remove_content_type_name	2026-07-25 21:47:44.417594+03:30
3	auth	0001_initial	2026-07-25 21:47:44.465349+03:30
4	auth	0002_alter_permission_name_max_length	2026-07-25 21:47:44.471372+03:30
5	auth	0003_alter_user_email_max_length	2026-07-25 21:47:44.483605+03:30
6	auth	0004_alter_user_username_opts	2026-07-25 21:47:44.493536+03:30
7	auth	0005_alter_user_last_login_null	2026-07-25 21:47:44.500721+03:30
8	auth	0006_require_contenttypes_0002	2026-07-25 21:47:44.505083+03:30
9	auth	0007_alter_validators_add_error_messages	2026-07-25 21:47:44.510824+03:30
10	auth	0008_alter_user_username_max_length	2026-07-25 21:47:44.516663+03:30
11	auth	0009_alter_user_last_name_max_length	2026-07-25 21:47:44.523525+03:30
12	auth	0010_alter_group_name_max_length	2026-07-25 21:47:44.536637+03:30
13	auth	0011_update_proxy_permissions	2026-07-25 21:47:44.542459+03:30
14	auth	0012_alter_user_first_name_max_length	2026-07-25 21:47:44.550349+03:30
15	accounts	0001_initial	2026-07-25 21:47:44.640674+03:30
16	admin	0001_initial	2026-07-25 21:47:44.665129+03:30
17	admin	0002_logentry_remove_auto_add	2026-07-25 21:47:44.677164+03:30
18	admin	0003_logentry_add_action_flag_choices	2026-07-25 21:47:44.68741+03:30
19	lodges	0001_initial	2026-07-25 21:47:44.710314+03:30
20	lodges	0002_alter_lodge_options_alter_lodge_active_and_more	2026-07-25 21:47:44.730043+03:30
21	sessions	0001_initial	2026-07-25 21:47:44.747018+03:30
22	lodges	0003_lodge_interests_lodge_owner	2026-07-25 22:08:29.965257+03:30
23	accounts	0002_rename_interest_interests_alter_profile_first_name_and_more	2026-08-01 18:24:28.471988+03:30
24	lodges	0004_alter_lodgeimage_image	2026-08-06 23:45:36.959351+03:30
25	reservations	0001_initial	2026-08-06 23:45:37.679221+03:30
26	lodges	0005_alter_lodge_capacity_alter_lodge_price_and_more	2026-08-14 21:16:55.969262+03:30
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: ecolodge_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
rlsp6k2sqsq0dwo7kk6040700lgb4kiq	.eJxVjMsOwiAQAP9lz4bwXKBH734D2cIiVdMmpT0Z_9006UGvM5N5Q6J9a2nvvKapwAAKLr9spPzk-RDlQfN9EXmZt3UaxZGI03ZxWwq_rmf7N2jUGwxQDbuoMOias0FvjEStnUUn2ZrgbfDF6cCkkLVFGQOhtDobripicQSfL6e8NmI:1wsfzM:C_IeLZnqAO7UwvD5R-uVuaGczkfOzQjctPxj9P-vVTg	2026-08-22 15:47:20.479528+03:30
\.


--
-- Data for Name: lodges_lodge; Type: TABLE DATA; Schema: public; Owner: ecolodge_user
--

COPY public.lodges_lodge (id, title, slug, description, province, city, address, capacity, price, active, status, owner_id) FROM stdin;
4	اقامتگاه 4	اقامتگاه-4	لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد	اصفهان	اصفهان	اصفهان, میدان	8	1400000	t	confirmed	1
10	اقامتگاه حسن 2	اقامتگاه-حسن-2	قفلتا2	فارس	شیراز	فارس, شیراز, خ شهید, پلاک 25	16	1200000	f	confirmed	3
3	اقامتگاه 3	اقامتگاه-3	لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. \r\nچاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد. \r\nدر این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.	مازندران	چالوس	مازندران, چالوس, خ شهید, پلاک 33	8	200000	t	confirmed	1
17	بهشت دنیوی	بهشت-دنیوی	شراب های بهشتی و رود های عسلی	گیلان	گلاب دره	گیلان , گلاب دره, خیابان شهید بهشتی, کوچه حوری اینا, پلاک 1, طبقه 7	3	10000000	t	confirmed	5
20	اقامتگاه هفتادم	اقامتگاه-هفتادم	پارکینگ دارد	مازندران	نوشهر	مازندران, نوشهر, خ شهید, کوی پنجم, پلاک 17	5	1000000	t	confirmed	1
19	لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم	لورم-ایپسوم-متن-ساختگی-با-تولید-سادگی-نامفهوم	لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد، در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.	مازندران	کلاردشت	مازندران,	2	2000000	t	confirmed	1
18	خانه آبی	خانه-آبی	چشمه آب طبیعی در اقامت خود.\r\nچشمه آبگرم خصوصی برای درمان انواع امراض و کیف و حال.\r\nبا صرف سرشیر گاومیش و عسل	اردبیل	سرعین	اردبیل-سرعین-خیابان جمهوری-جنب استخر دیبا	2	5000000	t	confirmed	6
16	our home	our-home	our home is so big and beuty	مازندران	کلاردشت	مازندران,	12	10000	t	confirmed	4
\.


--
-- Data for Name: lodges_lodge_interests; Type: TABLE DATA; Schema: public; Owner: ecolodge_user
--

COPY public.lodges_lodge_interests (id, lodge_id, interests_id) FROM stdin;
8	4	1
9	4	2
10	4	5
11	4	6
24	3	11
25	3	10
26	3	3
27	16	9
28	16	11
29	16	5
30	17	1
31	17	5
32	17	6
33	17	9
34	17	10
35	17	11
36	18	10
37	18	11
38	19	9
39	20	11
40	20	10
41	20	3
\.


--
-- Data for Name: lodges_lodgeimage; Type: TABLE DATA; Schema: public; Owner: ecolodge_user
--

COPY public.lodges_lodgeimage (id, image, lodge_id) FROM stdin;
4	lodgeimages/slider-2.jpg	3
5	lodgeimages/slider_2.jpg	3
6	lodgeimages/hero-slider-2.jpg	4
14	lodges/1/3/hero_1.jpg	3
16	lodges/4/16/gal_2.jpg	16
17	lodges/5/17/photorealistic-rainbow-with-countryside-nature-landscape_23-2151597629.avif	17
18	lodges/5/17/images.jpg	17
20	lodges/6/18/images_2.jpg	18
21	lodges/6/18/images_1.jpg	18
22	lodges/6/18/images_4.jpg	18
23	lodges/1/19/elena-baidak-pz69kY0UQuQ-unsplash.jpg	19
\.


--
-- Data for Name: reservations_reservation; Type: TABLE DATA; Schema: public; Owner: ecolodge_user
--

COPY public.reservations_reservation (id, guest_count, check_in, check_out, total_price, status, created_at, updated_at, lodge_id, user_id) FROM stdin;
10	6	2027-01-10	2027-01-16	100000000	t	2026-08-14 00:34:22.103124+03:30	2026-08-14 00:34:22.103134+03:30	10	6
17	2	2026-09-05	2026-09-07	10000000	t	2026-09-02 18:26:14.693549+03:30	2026-09-02 18:26:14.693559+03:30	18	3
20	2	2026-09-03	2026-09-04	200000	f	2026-09-02 20:53:07.874887+03:30	2026-09-02 20:53:18.069264+03:30	3	1
23	1	2026-09-03	2026-09-04	2000000	t	2026-09-02 21:06:39.432471+03:30	2026-09-02 21:06:39.43248+03:30	19	1
22	2	2026-09-26	2026-09-28	400000	f	2026-09-02 20:54:23.492126+03:30	2026-09-02 21:08:23.302277+03:30	3	1
19	4	2026-09-10	2026-09-12	400000	f	2026-09-02 18:31:09.619225+03:30	2026-09-02 21:08:26.462302+03:30	3	1
24	2	2026-09-15	2026-09-18	30000000	t	2026-09-03 15:33:07.986352+03:30	2026-09-03 15:33:07.986362+03:30	17	1
25	4	2026-09-24	2026-09-30	1200000	t	2026-09-03 16:06:33.366616+03:30	2026-09-03 16:06:33.366627+03:30	3	1
26	1	2026-09-03	2026-09-05	400000	t	2026-09-03 17:02:57.650248+03:30	2026-09-03 17:02:57.650259+03:30	3	1
29	1	2026-09-16	2026-09-17	2000000	t	2026-09-03 17:42:01.993828+03:30	2026-09-03 17:42:01.993844+03:30	19	3
30	1	2026-09-27	2026-09-28	10000000	t	2026-09-03 17:42:31.098914+03:30	2026-09-03 17:42:31.098936+03:30	17	3
31	1	2026-10-01	2026-10-02	10000000	t	2026-09-05 13:44:29.315618+03:30	2026-09-05 13:44:29.31564+03:30	17	3
32	1	2026-10-02	2026-10-03	10000000	t	2026-09-05 13:52:39.803556+03:30	2026-09-05 13:52:39.803566+03:30	17	1
33	1	2026-09-05	2026-09-07	400000	t	2026-09-05 13:53:27.700595+03:30	2026-09-05 13:53:27.700604+03:30	3	3
34	2	2026-09-09	2026-09-12	15000000	t	2026-09-05 16:26:11.999359+03:30	2026-09-05 16:26:11.999374+03:30	18	3
36	2	2026-09-21	2026-09-22	5000000	f	2026-09-05 16:34:01.921933+03:30	2026-09-05 16:34:30.748745+03:30	18	1
37	1	2026-09-12	2026-09-15	600000	t	2026-09-05 16:40:23.189711+03:30	2026-09-05 16:40:23.189723+03:30	3	1
39	1	2027-01-10	2027-01-16	1200000	t	2026-09-05 18:24:46.177575+03:30	2026-09-05 18:24:46.177584+03:30	3	1
40	2	2026-09-17	2026-09-18	2000000	t	2026-09-05 21:11:39.911905+03:30	2026-09-05 21:11:39.911917+03:30	19	10
41	2	2026-09-07	2026-09-10	6000000	t	2026-09-05 21:12:14.450557+03:30	2026-09-05 21:12:14.450577+03:30	19	10
35	2	2026-09-15	2026-09-19	20000000	f	2026-09-05 16:28:54.346873+03:30	2026-09-05 21:45:31.84757+03:30	18	3
42	1	2026-09-16	2026-09-18	10000000	t	2026-09-05 21:47:16.441165+03:30	2026-09-05 21:47:16.441175+03:30	18	10
43	1	2026-09-07	2026-09-09	400000	t	2026-09-05 23:29:50.522361+03:30	2026-09-05 23:29:50.522374+03:30	3	3
44	1	2026-10-26	2026-10-28	4000000	t	2026-09-06 08:06:23.702935+03:30	2026-09-06 08:06:23.702951+03:30	19	3
\.


--
-- Name: accounts_interest_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ecolodge_user
--

SELECT pg_catalog.setval('public.accounts_interest_id_seq', 12, true);


--
-- Name: accounts_profile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ecolodge_user
--

SELECT pg_catalog.setval('public.accounts_profile_id_seq', 9, true);


--
-- Name: accounts_profile_interests_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ecolodge_user
--

SELECT pg_catalog.setval('public.accounts_profile_interests_id_seq', 36, true);


--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ecolodge_user
--

SELECT pg_catalog.setval('public.accounts_user_groups_id_seq', 1, false);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ecolodge_user
--

SELECT pg_catalog.setval('public.accounts_user_id_seq', 10, true);


--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ecolodge_user
--

SELECT pg_catalog.setval('public.accounts_user_user_permissions_id_seq', 48, true);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ecolodge_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ecolodge_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ecolodge_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 48, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ecolodge_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 57, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ecolodge_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 11, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ecolodge_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 26, true);


--
-- Name: lodges_lodge_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ecolodge_user
--

SELECT pg_catalog.setval('public.lodges_lodge_id_seq', 20, true);


--
-- Name: lodges_lodge_interests_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ecolodge_user
--

SELECT pg_catalog.setval('public.lodges_lodge_interests_id_seq', 41, true);


--
-- Name: lodges_lodgeimage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ecolodge_user
--

SELECT pg_catalog.setval('public.lodges_lodgeimage_id_seq', 23, true);


--
-- Name: reservations_reservation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ecolodge_user
--

SELECT pg_catalog.setval('public.reservations_reservation_id_seq', 44, true);


--
-- Name: accounts_interests accounts_interest_pkey; Type: CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.accounts_interests
    ADD CONSTRAINT accounts_interest_pkey PRIMARY KEY (id);


--
-- Name: accounts_profile_interests accounts_profile_interests_pkey; Type: CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.accounts_profile_interests
    ADD CONSTRAINT accounts_profile_interests_pkey PRIMARY KEY (id);


--
-- Name: accounts_profile_interests accounts_profile_interests_profile_id_interest_id_aab481d8_uniq; Type: CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.accounts_profile_interests
    ADD CONSTRAINT accounts_profile_interests_profile_id_interest_id_aab481d8_uniq UNIQUE (profile_id, interests_id);


--
-- Name: accounts_profile accounts_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.accounts_profile
    ADD CONSTRAINT accounts_profile_pkey PRIMARY KEY (id);


--
-- Name: accounts_profile accounts_profile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.accounts_profile
    ADD CONSTRAINT accounts_profile_user_id_key UNIQUE (user_id);


--
-- Name: accounts_user_groups accounts_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_groups accounts_user_groups_user_id_group_id_59c0b32f_uniq; Type: CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_group_id_59c0b32f_uniq UNIQUE (user_id, group_id);


--
-- Name: accounts_user accounts_user_pkey; Type: CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq; Type: CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq UNIQUE (user_id, permission_id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: accounts_user accounts_user_username_key; Type: CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_username_key UNIQUE (username);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: lodges_lodge_interests lodges_lodge_interests_lodge_id_interest_id_0c4bb139_uniq; Type: CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.lodges_lodge_interests
    ADD CONSTRAINT lodges_lodge_interests_lodge_id_interest_id_0c4bb139_uniq UNIQUE (lodge_id, interests_id);


--
-- Name: lodges_lodge_interests lodges_lodge_interests_pkey; Type: CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.lodges_lodge_interests
    ADD CONSTRAINT lodges_lodge_interests_pkey PRIMARY KEY (id);


--
-- Name: lodges_lodge lodges_lodge_pkey; Type: CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.lodges_lodge
    ADD CONSTRAINT lodges_lodge_pkey PRIMARY KEY (id);


--
-- Name: lodges_lodge lodges_lodge_slug_key; Type: CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.lodges_lodge
    ADD CONSTRAINT lodges_lodge_slug_key UNIQUE (slug);


--
-- Name: lodges_lodgeimage lodges_lodgeimage_pkey; Type: CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.lodges_lodgeimage
    ADD CONSTRAINT lodges_lodgeimage_pkey PRIMARY KEY (id);


--
-- Name: reservations_reservation reservations_reservation_pkey; Type: CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.reservations_reservation
    ADD CONSTRAINT reservations_reservation_pkey PRIMARY KEY (id);


--
-- Name: accounts_profile_interests_interest_id_fcb1dbe7; Type: INDEX; Schema: public; Owner: ecolodge_user
--

CREATE INDEX accounts_profile_interests_interest_id_fcb1dbe7 ON public.accounts_profile_interests USING btree (interests_id);


--
-- Name: accounts_profile_interests_profile_id_e30c47b7; Type: INDEX; Schema: public; Owner: ecolodge_user
--

CREATE INDEX accounts_profile_interests_profile_id_e30c47b7 ON public.accounts_profile_interests USING btree (profile_id);


--
-- Name: accounts_user_groups_group_id_bd11a704; Type: INDEX; Schema: public; Owner: ecolodge_user
--

CREATE INDEX accounts_user_groups_group_id_bd11a704 ON public.accounts_user_groups USING btree (group_id);


--
-- Name: accounts_user_groups_user_id_52b62117; Type: INDEX; Schema: public; Owner: ecolodge_user
--

CREATE INDEX accounts_user_groups_user_id_52b62117 ON public.accounts_user_groups USING btree (user_id);


--
-- Name: accounts_user_user_permissions_permission_id_113bb443; Type: INDEX; Schema: public; Owner: ecolodge_user
--

CREATE INDEX accounts_user_user_permissions_permission_id_113bb443 ON public.accounts_user_user_permissions USING btree (permission_id);


--
-- Name: accounts_user_user_permissions_user_id_e4f0a161; Type: INDEX; Schema: public; Owner: ecolodge_user
--

CREATE INDEX accounts_user_user_permissions_user_id_e4f0a161 ON public.accounts_user_user_permissions USING btree (user_id);


--
-- Name: accounts_user_username_6088629e_like; Type: INDEX; Schema: public; Owner: ecolodge_user
--

CREATE INDEX accounts_user_username_6088629e_like ON public.accounts_user USING btree (username varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: ecolodge_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: ecolodge_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: ecolodge_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: ecolodge_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: ecolodge_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: ecolodge_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: ecolodge_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: ecolodge_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: lodges_lodge_interests_interest_id_4d024519; Type: INDEX; Schema: public; Owner: ecolodge_user
--

CREATE INDEX lodges_lodge_interests_interest_id_4d024519 ON public.lodges_lodge_interests USING btree (interests_id);


--
-- Name: lodges_lodge_interests_lodge_id_1f2afc10; Type: INDEX; Schema: public; Owner: ecolodge_user
--

CREATE INDEX lodges_lodge_interests_lodge_id_1f2afc10 ON public.lodges_lodge_interests USING btree (lodge_id);


--
-- Name: lodges_lodge_owner_id_46ff4743; Type: INDEX; Schema: public; Owner: ecolodge_user
--

CREATE INDEX lodges_lodge_owner_id_46ff4743 ON public.lodges_lodge USING btree (owner_id);


--
-- Name: lodges_lodge_slug_fdd1b40d_like; Type: INDEX; Schema: public; Owner: ecolodge_user
--

CREATE INDEX lodges_lodge_slug_fdd1b40d_like ON public.lodges_lodge USING btree (slug varchar_pattern_ops);


--
-- Name: lodges_lodgeimage_lodge_id_43154354; Type: INDEX; Schema: public; Owner: ecolodge_user
--

CREATE INDEX lodges_lodgeimage_lodge_id_43154354 ON public.lodges_lodgeimage USING btree (lodge_id);


--
-- Name: reservations_reservation_lodge_id_b4c22fc9; Type: INDEX; Schema: public; Owner: ecolodge_user
--

CREATE INDEX reservations_reservation_lodge_id_b4c22fc9 ON public.reservations_reservation USING btree (lodge_id);


--
-- Name: reservations_reservation_user_id_6ed5b1c9; Type: INDEX; Schema: public; Owner: ecolodge_user
--

CREATE INDEX reservations_reservation_user_id_6ed5b1c9 ON public.reservations_reservation USING btree (user_id);


--
-- Name: accounts_profile_interests accounts_profile_int_interests_id_cc7a74be_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.accounts_profile_interests
    ADD CONSTRAINT accounts_profile_int_interests_id_cc7a74be_fk_accounts_ FOREIGN KEY (interests_id) REFERENCES public.accounts_interests(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_profile_interests accounts_profile_int_profile_id_e30c47b7_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.accounts_profile_interests
    ADD CONSTRAINT accounts_profile_int_profile_id_e30c47b7_fk_accounts_ FOREIGN KEY (profile_id) REFERENCES public.accounts_profile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_profile accounts_profile_user_id_49a85d32_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.accounts_profile
    ADD CONSTRAINT accounts_profile_user_id_49a85d32_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_groups accounts_user_groups_group_id_bd11a704_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_group_id_bd11a704_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_groups accounts_user_groups_user_id_52b62117_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_52b62117_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_permission_id_113bb443_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_permission_id_113bb443_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_user_id_e4f0a161_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_user_id_e4f0a161_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: lodges_lodge_interests lodges_lodge_interes_interests_id_9843ef40_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.lodges_lodge_interests
    ADD CONSTRAINT lodges_lodge_interes_interests_id_9843ef40_fk_accounts_ FOREIGN KEY (interests_id) REFERENCES public.accounts_interests(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: lodges_lodge_interests lodges_lodge_interests_lodge_id_1f2afc10_fk_lodges_lodge_id; Type: FK CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.lodges_lodge_interests
    ADD CONSTRAINT lodges_lodge_interests_lodge_id_1f2afc10_fk_lodges_lodge_id FOREIGN KEY (lodge_id) REFERENCES public.lodges_lodge(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: lodges_lodge lodges_lodge_owner_id_46ff4743_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.lodges_lodge
    ADD CONSTRAINT lodges_lodge_owner_id_46ff4743_fk_accounts_user_id FOREIGN KEY (owner_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: lodges_lodgeimage lodges_lodgeimage_lodge_id_43154354_fk_lodges_lodge_id; Type: FK CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.lodges_lodgeimage
    ADD CONSTRAINT lodges_lodgeimage_lodge_id_43154354_fk_lodges_lodge_id FOREIGN KEY (lodge_id) REFERENCES public.lodges_lodge(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reservations_reservation reservations_reservation_lodge_id_b4c22fc9_fk_lodges_lodge_id; Type: FK CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.reservations_reservation
    ADD CONSTRAINT reservations_reservation_lodge_id_b4c22fc9_fk_lodges_lodge_id FOREIGN KEY (lodge_id) REFERENCES public.lodges_lodge(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reservations_reservation reservations_reservation_user_id_6ed5b1c9_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: ecolodge_user
--

ALTER TABLE ONLY public.reservations_reservation
    ADD CONSTRAINT reservations_reservation_user_id_6ed5b1c9_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict BVIDiuOOoJmcpWybptcyLrcDNGoTb7Tg5I5XSfY64tmmcNYKerQswyCyccmMcwt

