# Generated by Django 6.0.7 on 2026-09-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='check_in',
            field=models.DateField(verbose_name='تاریخ ورود'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_out',
            field=models.DateField(verbose_name='تاریخ خروج'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest_count',
            field=models.PositiveIntegerField(verbose_name='تعداد مسافران'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_price',
            field=models.PositiveIntegerField(verbose_name='قیمت نهایی'),
        ),
    ]
