# Generated by Django 6.0.7 on 2026-08-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('lodges', '0003_lodge_interests_lodge_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interest',
            new_name='Interests',
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='owner',
            field=models.BooleanField(default=False, verbose_name='آیا میزبان اقامتگاه هستی؟'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
