# Generated by Django 6.0.7 on 2026-07-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lodge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True)),
                ('description', models.TextField()),
                ('province', models.CharField()),
                ('city', models.CharField()),
                ('address', models.TextField()),
                ('capacity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('active', models.BooleanField(default=False)),
                ('status', models.CharField()),
            ],
        ),
    ]
