# Generated by Django 6.0.7 on 2026-07-25 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lodge',
            options={'verbose_name': 'اقامتگاه', 'verbose_name_plural': 'اقامتگاه ها'},
        ),
        migrations.AlterField(
            model_name='lodge',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lodge',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تایید'), ('confirmed', 'تایید شده'), ('canclled', 'رد شده')], default='pending'),
        ),
        migrations.CreateModel(
            name='LodgeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lodgeimages/')),
                ('lodge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lodges.lodge')),
            ],
        ),
    ]
