# Generated by Django 6.0.7 on 2026-07-14 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0002_alter_lodge_options_alter_lodge_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgeimage',
            name='lodge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lodges.lodge'),
        ),
    ]
