# Generated by Django 6.0.7 on 2026-07-25 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('lodges', '0002_alter_lodge_options_alter_lodge_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lodge',
            name='interests',
            field=models.ManyToManyField(blank=True, to='accounts.interest'),
        ),
        migrations.AddField(
            model_name='lodge',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lodges', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
