# Generated by Django 6.0.7 on 2026-08-06 20:15

import lodges.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0003_lodge_interests_lodge_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgeimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=lodges.models.lodge_image_path),
        ),
    ]
