# Generated by Django 6.0.7 on 2026-08-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0004_alter_lodgeimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodge',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='lodge',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='lodge',
            name='province',
            field=models.CharField(choices=[('مازندران', 'مازندران'), ('گیلان', 'گیلان'), ('گلستان', 'گلستان'), ('تهران', 'تهران'), ('البرز', 'البرز'), ('اردبیل', 'اردبیل')]),
        ),
    ]
