# Generated by Django 6.0.7 on 2026-09-12 18:00

import lodges.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_first_name_alter_profile_interests_and_more'),
        ('lodges', '0005_alter_lodge_capacity_alter_lodge_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodge',
            name='active',
            field=models.BooleanField(default=True, verbose_name='فعال بودن'),
        ),
        migrations.AlterField(
            model_name='lodge',
            name='address',
            field=models.TextField(verbose_name='آدرس کامل'),
        ),
        migrations.AlterField(
            model_name='lodge',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='ظرفیت اقامتگاه'),
        ),
        migrations.AlterField(
            model_name='lodge',
            name='city',
            field=models.CharField(verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='lodge',
            name='description',
            field=models.TextField(verbose_name='توضیحات و امکانات'),
        ),
        migrations.AlterField(
            model_name='lodge',
            name='interests',
            field=models.ManyToManyField(blank=True, to='accounts.interests', verbose_name='جاذبه ها'),
        ),
        migrations.AlterField(
            model_name='lodge',
            name='price',
            field=models.PositiveIntegerField(verbose_name='قیمت هر شب'),
        ),
        migrations.AlterField(
            model_name='lodge',
            name='province',
            field=models.CharField(choices=[('اردبیل', 'اردبیل'), ('اصفهان', 'اصفهان'), ('خراسان رضوی', 'خراسان رضوی'), ('فارس', 'فارس'), ('گیلان', 'گیلان'), ('گلستان', 'گلستان'), ('مازندران', 'مازندران')], verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='lodge',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تایید'), ('confirmed', 'تایید شده'), ('canclled', 'رد شده')], default='pending', verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='lodgeimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=lodges.models.lodge_image_path, verbose_name='عکس'),
        ),
    ]
